### PR TITLE
add path to os/codec to find the headers

### PR DESCRIPTION
**Pull request by Begasus**
This will fix the not found headers, doesn't fix the build tho

### CODE REVIEW

**Comment by Begasus** [comment]
Ok, got it to build here, and playing, could use some checking (not a developer here) :)
(used Barret's suggestion in the issue https://github.com/HaikuArchives/Haiku-Radio/issues/3)

**Comment by Begasus** [comment]
My primary target was x86_gcc2 where this PR was issued and works, for x86_64 StreamRadio still builds out of the box (and runs fine)?

**Comment by Begasus** [comment]
This patch should "not" be imported, as it looks now the changes to "os/codec" want be imported soon in the Haiku Beta, so it would break it there

**Comment by Begasus** [comment]
If there is a way to check for nightly or beta it somehow could be applied

**Comment by diversys** [comment]
Codec Kit was reverted.

**Pull request closed without merging**
